export const STRINGS = {
  common: {
    ok: "Tamam",
    cancel: "İptal",
    save: "Kaydet",
    reset: "Sıfırla",
    apply: "Uygula",
    error: "Hata",
    success: "Başarılı",
    loading: "Yükleniyor...",
    retry: "Tekrar Dene",
    notFound: "Bulunamadı",
  },
  tabs: {
    home: "Anasayfa",
    search: "Ara",
    messages: "Mesajlar",
    profile: "Profil",
  },
  notifications: {
    title: "Bildirimler",
    empty: "Henüz bildirimin yok.",
    markAllRead: "Tümünü Okundu Yap",
    markedAllRead: "Tüm bildirimler okundu olarak işaretlendi.",
    loadError: "Bildirimler yüklenemedi.",
  },
  favorites: {
    title: "Favorilerim",
    empty: "Henüz favori ilan eklemedin.",
  },
  myListings: {
    title: "İlanlarım",
    active: "Aktif",
    sold: "Satıldı",
    deleted: "Silinen",
    empty: "Bu sekmede ilan bulunmuyor.",
  },
  filters: {
    title: "Gelişmiş Filtre",
    condition: "Durum",
    minPrice: "Minimum Fiyat",
    maxPrice: "Maksimum Fiyat",
    sort: "Sıralama",
  },
  profile: {
    quickAccessTitle: "Hızlı Erişim",
    contactSettingsTitle: "Gizlilik ve İletişim Ayarları",
    contactWhatsapp: "WhatsApp ile iletişime izin ver",
    contactEmail: "E-posta ile iletişime izin ver",
    pushEnabled: "Push bildirimleri açık",
  },
  reports: {
    reportTitle: "İlanı Şikayet Et",
    reportPrompt: "Şikayet nedenini seç",
    spam: "Spam",
    misleading: "Yanıltıcı Bilgi",
    inappropriate: "Uygunsuz İçerik",
    other: "Diğer",
    submitted: "Şikayetin alındı. Teşekkür ederiz.",
  },
} as const;
